stages:
  - build

.build:
  tags:
    - docker
  stage: build
  image: debian:trixie
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    # Install dependencies
    - apt update && apt install -y
      build-essential
      cmake
      git
      zlib1g-dev
      wget

    # Build boost
    - boost="boost_"$BOOST_MAJOR"_"$BOOST_MINOR"_"$BOOST_PATCH
    - BOOST_VERSION=$BOOST_MAJOR"."$BOOST_MINOR"."$BOOST_PATCH
    - wget --quiet "https://archives.boost.io/release/"$BOOST_VERSION"/source/"$boost".tar.bz2"
    - tar -xjf $boost".tar.bz2"
    - cd $boost
    - ./bootstrap.sh --prefix=/usr/local
    - b2_options="--link=static --with-system --with-test --with-context"
    - if [[ $BOOST_MINOR -lt 80 ]]; then b2_options=$b2_options" --with-coroutine"; fi
    - ./b2 -j3 -d+0 $b2_options install
    - cd ..

    # Build asio-utp
    - cmake -S ./ -B build/asio-utp
      -DBOOST_VERSION=$BOOST_VERSION
      -DASIO_UTP_WITH_TESTS=ON
      -DASIO_UTP_WITH_EXAMPLES=OFF
      -DASIO_UTP_DEBUG_LOGGING=OFF
      -DUTP_DEBUG_LOGGING=OFF
    - cmake --build build/asio-utp
    - export LD_LIBRARY_PATH=$CI_PROJECT_DIR/$boost/stage/lib:$LD_LIBRARY_PATH

    # Run the tests
    - ./build/asio-utp/asio_utp_test_comm
    - ./build/asio-utp/asio_utp_test_util

    # Run the benchmark
    - ./build/asio-utp/asio_utp_test_bench server utp 127.0.0.1:6789&
    - ./build/asio-utp/asio_utp_test_bench client utp 127.0.0.1:6789

boost-1.87:
  extends: ".build"
  variables:
    BOOST_MAJOR: "1"
    BOOST_MINOR: "87"
    BOOST_PATCH: "0"
