image: debian:buster

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  variables:
     BOOST_MAJOR: "1"
     BOOST_MINOR: "71"
     BOOST_PATCH: "0"
  tags:
    - docker
  script:
    # Install dependencies
    - apt update && apt install -y
        build-essential
        cmake
        git
        zlib1g-dev
        wget

    # Build boost
    - boost="boost_"$BOOST_MAJOR"_"$BOOST_MINOR"_"$BOOST_PATCH
    - wget "https://boostorg.jfrog.io/artifactory/main/release/"$BOOST_MAJOR"."$BOOST_MINOR"."$BOOST_PATCH"/source/"$boost".tar.bz2"
    - tar -xjf $boost".tar.bz2"
    - cd $boost
    - ./bootstrap.sh
    - ./b2 -j3 -d+0 --link=static --with-system --with-test --with-coroutine
    - cd ..

    # Build asio-utp
    - cmake -S ./ -B build/asio-utp
        -DBOOST_ROOT=$CI_PROJECT_DIR/build/boost/boost/install/
        -DASIO_UTP_WITH_TESTS=OFF
        -DASIO_UTP_WITH_EXAMPLES=OFF
        -DASIO_UTP_DEBUG_LOGGING=OFF
        -DUTP_DEBUG_LOGGING=OFF
    - cmake --build build/asio-utp
